# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Write the goal-conditioned expert's acceptance probes as plan files.

``expert_revist/expert_revisit.MD`` §3.5 pre-registers two tests for the
expert, and both are goal sequences the in-training panel (``SequenceViz``)
and the standalone driver (``run_sequence_panel.py``) can run unchanged:

* **fork** -- start at a family's own clip at t = 0 (the standing rest), command
  the family hold with the clip's own entry time as the deadline, hold it, then
  command the clip's closing ``standing``. Whether the policy enters the
  *commanded* pose from the shared standing start is the one number that says
  it is goal-conditioned; the panel's per-goal ``hold_pose_err`` and the
  offline ``score_probe_pose.py`` confusion matrix read it.
* **dwell** -- start *at* the hold, command it for ``d`` seconds
  (``--dwell-seconds``, default 3 / 6 / 10), then the exit to standing. The
  exit time must follow ``dwell_remaining``, not the pose.

Plans name nodes by their graph key (``NAME|GROUND@ORIENT``) and poses by the
exact clip stem (the panel resolves exact stems first, so the ``_x3s`` /
``_x7s`` variants cannot shadow the source), and take the pose from the
**unextended** clip so a plan does not depend on which variant is in the
corpus. Generated per family, or for ``--families`` only.

Usage::

    PYTHONPATH=. python data/scripts/make_hold_graph_probe_plans.py \
      --graph data/smpl/yoga_hold_graph_expert60/contact_graph.json \
      --out-dir data/scripts/plans_expert60
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent


def _slug(text: str, limit: int = 40) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "_", text).strip("_")
    return slug[:limit].strip("_")


def family_plans(
    graph: dict,
    hold_s: float = 4.0,
    dwell_seconds: tuple = (3.0, 6.0, 10.0),
    max_reach_s: float = 10.0,
    max_exit_s: float = 6.0,
) -> dict:
    """``{plan_name: plan}`` for every family in ``graph`` (pure; unit-tested).

    Uses only the ``variant_s == 0`` clips. For a family with several source
    clips the one with the longest family hold is the exemplar.
    """
    nodes = graph["nodes"]
    best = {}  # family -> (duration, stem, segment index, clip record)
    for stem, clip in graph["clips"].items():
        # Unextended clips only: variant_s == 0, and the stem is its own source.
        if float(clip.get("variant_s", 0.0)) != 0.0:
            continue
        if clip.get("source_stem", stem) != stem:
            continue
        family = clip.get("family") or stem
        for k, seg in enumerate(clip["segments"]):
            if seg["name"] != family:
                continue
            if family not in best or seg["duration_s"] > best[family][0]:
                best[family] = (seg["duration_s"], stem, k, clip)

    plans = {}
    for family, (_dur, stem, k, clip) in sorted(best.items()):
        segments = clip["segments"]
        hold = segments[k]
        closing = next(
            (s for s in reversed(segments) if s["name"] == "standing" and s["t_start"] > hold["t_end"]),
            None,
        )
        opening = segments[0] if segments and segments[0]["t_start"] == 0.0 else None
        hold_key = nodes[hold["node"]]["key"]
        goal_hold = {
            "name": family[:24],
            "config": hold_key,
            "pose_clip": stem,
            "pose_time": hold["t_hold"],
        }
        exit_goals = []
        if closing is not None:
            exit_goals.append(
                {
                    "name": "standing",
                    "config": nodes[closing["node"]]["key"],
                    "pose_clip": stem,
                    "pose_time": closing["t_hold"],
                    "reach_s": round(min(max(closing["t_start"] - hold["t_end"], 1.0), max_exit_s), 2),
                    "hold_s": 2.0,
                }
            )

        slug = _slug(family)
        # Fork: from the clip's own start, the entry the reference took.
        entry = hold["t_start"] - (opening["t_end"] if opening else 0.0)
        plans[f"fork_{slug}"] = {
            "_comment": [
                f"Fork test for {family}: enter the commanded hold from the standing start",
                f"of {stem} in the reference's own entry time, hold {hold_s:.0f} s, return to standing.",
                "Generated by data/scripts/make_hold_graph_probe_plans.py.",
            ],
            "start": {"clip": stem, "time": 0.0},
            "goals": [
                {**goal_hold, "reach_s": round(min(max(entry, 1.0), max_reach_s), 2), "hold_s": hold_s},
                *exit_goals,
            ],
        }
        # Dwell: start at the hold, stay d seconds, then leave.
        for d in dwell_seconds:
            plans[f"dwell_{slug}_{int(round(d))}s"] = {
                "_comment": [
                    f"Dwell test for {family}: placed at the hold, commanded to stay {d:.0f} s,",
                    "then commanded the clip's closing standing. The exit must follow",
                    "dwell_remaining, not the pose. Generated by make_hold_graph_probe_plans.py.",
                ],
                "start": {"clip": stem, "time": hold["t_hold"]},
                "goals": [
                    {**goal_hold, "reach_s": 0.5, "hold_s": float(d)},
                    *exit_goals,
                ],
            }
    return plans


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--graph", default="data/smpl/yoga_hold_graph_expert60/contact_graph.json")
    parser.add_argument("--out-dir", default="data/scripts/plans_expert60")
    parser.add_argument("--families", nargs="*", default=None, help="Family-name substrings to keep.")
    parser.add_argument("--hold-seconds", type=float, default=4.0)
    parser.add_argument("--dwell-seconds", type=float, nargs="+", default=[3.0, 6.0, 10.0])
    args = parser.parse_args()

    graph_path = Path(args.graph)
    if not graph_path.is_absolute():
        graph_path = REPO_ROOT / graph_path
    graph = json.load(open(graph_path))
    plans = family_plans(graph, hold_s=args.hold_seconds, dwell_seconds=tuple(args.dwell_seconds))
    if args.families:
        plans = {
            name: plan for name, plan in plans.items()
            if any(f.lower() in name.lower() for f in args.families)
        }
    out_dir = Path(args.out_dir)
    if not out_dir.is_absolute():
        out_dir = REPO_ROOT / out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, plan in plans.items():
        (out_dir / f"{name}.json").write_text(json.dumps(plan, indent=2))
    forks = sum(1 for n in plans if n.startswith("fork_"))
    print(f"wrote {len(plans)} plans ({forks} fork, {len(plans) - forks} dwell) to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
